version: '3.7'
services:
  es-db:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.17.0'
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      discovery.type: 'single-node'
      xpack.security.http.ssl.enabled: 'false'
      xpack.license.self_generated.type: 'trial'
      ELASTIC_PASSWORD: $ES_DB_PASSWORD
    volumes:
      - 'elastic-search-data:/usr/share/elasticsearch/data'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ['CMD-SHELL', 'curl http://localhost:9200']
      interval: 10s
      timeout: 10s
      retries: 120
volumes:
  elastic-search-data:
