export const SYNC_ACCOUNT_FOLDERS_EVENT = 'SYNC_ACCOUNT_FOLDERS_EVENT' as const;
export const SYNC_ACCOUNT_MESSAGES_EVENT =
  'SYNC_ACCOUNT_MESSAGES_EVENT' as const;
export const MARK_MESSAGE_AS_READ = 'MARK_MESSAGE_AS_READ' as const;
export const USER_SSE_RESPONSE = 'USER_SSE_RESPONSE' as const;
